name: Build and Release ValidFlow

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write

jobs:
  build-backend:
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install Pipenv & Dependencies
        working-directory: validflow-backend
        run: |
          pip install pipenv
          pipenv install --deploy --ignore-pipfile

      - name: Build Backend Binary
        working-directory: validflow-backend
        run: |
          pipenv run python build-backend.py

      - name: Upload Backend Artifact
        uses: actions/upload-artifact@v3
        with:
          name: backend-${{ matrix.os }}
          path: validflow-frontend/src-tauri/bin/start*

  build-and-release-app:
    needs: build-backend
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      - name: Cache Node Modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Cache Rust
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Install required dependencies on Windows
        if: runner.os == 'Windows'
        run: |
          choco install visualstudio2022buildtools visualstudio2022-workload-vctools -y
          rustup target add x86_64-pc-windows-msvc

      - name: Install dependencies on Linux
        if: runner.os == 'Linux'
        run: |
          sudo apt update
          sudo apt install -y libwebkit2gtk-4.0-dev libgtk-3-dev \
            libayatana-appindicator3-dev librsvg2-dev

      - name: Download Backend Binary
        uses: actions/download-artifact@v3
        with:
          name: backend-${{ matrix.os }}
          path: validflow-frontend/src-tauri/bin

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Install Frontend Dependencies
        working-directory: validflow-frontend
        run: npm install

      - name: Build Frontend
        working-directory: validflow-frontend
        run: npm run build

      - name: Build Tauri App
        working-directory: validflow-frontend
        run: npm run tauri build

      - name: Upload Release Artifacts
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          files: |
            validflow-frontend/src-tauri/target/release/*.exe
            validflow-frontend/src-tauri/target/release/bundle/**/*.msi
            validflow-frontend/src-tauri/target/release/bundle/**/*.dmg
            validflow-frontend/src-tauri/target/release/bundle/**/*.app
            validflow-frontend/src-tauri/target/release/bundle/**/*.AppImage
            validflow-frontend/src-tauri/target/release/bundle/**/*.deb
            validflow-frontend/src-tauri/target/release/bundle/**/*.rpm
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
